### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by bakirillov** [bmds-lab/Crackling#1]
Dear authors,

```g++ -o search_ots_score search_ots_score.cpp -O3 -std=c++11 -fopenmp -mpopcnt```

fails with 

```search_ots_score.cpp:34:10: fatal error: phmap.h: No such file or directory
   34 | #include <phmap.h>
      |          ^~~~~~~~~
compilation terminated.
```
despite phmap.h being present.
What am I doing wrong?

**Comment by bakirillov** [comment]
This command worked: ```g++ -o search_ots_score search_ots_score.cpp -O3 -std=c++11 -fopenmp -mpopcnt -Iparallel_hashmap```.

Could you please change it in the description?

**Comment by jakeb1996** [comment]
Hi @bakirillov ,

I've fixed this on the branch _master_. 

In branch _dev/v1.1.0_, the binaries and their source are renamed. The readme reflects this and have appropriate commands needed. These changes will be merged into _master_ soon.

Cheers,
